const mongoose = require('mongoose');

const paymentSchema = new mongoose.Schema({
  eventId: {
    type: String,
    required: true,
    unique: true
  },
  userId: {
    type: String,
    required: true
  },
  orderId: {
    type: String,
    required: false // Generated by Stripe
  },
  plan: {
    type: String,
    enum: ['BASIC', 'STANDARD', 'PRO'],
    required: true
  },
  amount: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    enum: ['PENDING', 'SUCCESS', 'FAILED'],
    default: 'PENDING'
  }
}, { timestamps: true });

module.exports = mongoose.model('Payment', paymentSchema);
